[#persian]
= سایت مستندات Asciidoctor
:icons: font

به سایت مستندات Asciidoctor خوش آمدید! در اینجا می‌توانید مطالب مرجع، راهنماها و نمونه‌های لازم برای نوشتن محتوا در AsciiDoc و انتشار آن با استفاده از Asciidoctor را پیدا کنید. این مستندات به شما کمک می‌کند سفر خود را با AsciiDoc آغاز کنید یا اگر قبلاً در مسیر خود هستید، عمیق‌تر شوید.

== درباره AsciiDoc بیاموزید

AsciiDoc یک فرمت نگارش متن ساده (یعنی زبان نشانه‌گذاری سبک) برای نوشتن محتوای فنی مانند مستندات، مقالات و کتاب‌ها است. اگر تازه با AsciiDoc شروع کرده‌اید، یا می‌خواهید کشف کنید که درباره چیست، به مستندات زبان AsciiDoc مراجعه کنید. از چگونگی ساخت اولین سند AsciiDoc خود تا استفاده از ویژگی‌های پیشرفته زبان مانند ادامه لیست‌ها و سفارشی‌سازی جایگزینی‌ها را خواهید آموخت.

اگر به یک یادآوری فشرده نیاز دارید، یا می‌خواهید نگاهی اجمالی به قابلیت‌های AsciiDoc داشته باشید، به مرجع سریع نحو مراجعه کنید. همچنین می‌توانید یک مقایسه کنار هم با Markdown پیدا کنید اگر به دنبال ارتقا هستید.

== پردازش محتوای AsciiDoc خود

مستندات زبان AsciiDoc عمدتاً درباره منبعی است که برای تألیف یک سند تایپ می‌کنید. هنگامی که نوشتن را تمام کردید و می‌خواهید سند AsciiDoc خود را منتشر کنید، به یک پردازنده AsciiDoc نیاز خواهید داشت. اینجاست که Asciidoctor وارد می‌شود.

Asciidoctor پردازنده اصلی AsciiDoc است. منبع AsciiDoc را می‌خواند، آن را به یک مدل سند تجزیه می‌کند، و با استفاده از یک مبدل آن را به یک فرمت قابل انتشار مانند HTML تبدیل می‌کند. Asciidoctor هم CLI و هم API دارد که می‌توانید برای فراخوانی یک مبدل داخلی (HTML، DocBook، صفحه man) یا یک مبدل افزودنی استفاده کنید. Asciidoctor HTML تولید شده از AsciiDoc را با اعمال یک صفحه‌آرایی پیش‌فرض، افزودن آیکون‌های سبک‌دار، و برجسته‌سازی نحوی بلوک‌های منبع، غنی می‌کند.